### PR TITLE
refactor: separate CE/EE code into apps/api/src/ee/

### PR DESCRIPTION
**Pull request by briceth**
## Summary

- Moves all Enterprise Edition code (alerting, Slack/webhook integrations, topology router, data export router, notification emails, alert cron worker) into a dedicated `apps/api/src/ee/` subtree to establish a clean open-core CE/EE boundary
- Adds `apps/api/src/ee/LICENSE` — proprietary header covering all EE code
- Adds `.github/workflows/sync-public-mirror.yml` — GitHub Actions workflow that rsyncs CE-only code (excluding `ee/`) to the public mirror repo on every push to `main` (requires `PUBLIC_REPO_TOKEN` secret on this repo)
- Updates all import paths in CE callers and within EE files; fixes broken relative imports that crossed the CE/EE boundary
- Fixes stale EE import paths in `apps/api/scripts/webhook/test-webhook.ts`

## Files moved to `ee/`

| Source | Destination |
|--------|-------------|
| `src/cron/rabbitmq-alerts.cron.ts` | `src/ee/cron/` |
| `src/workers/alert-monitor.ts` | `src/ee/workers/` |
| `src/services/alerts/` (9 files + 5 tests) | `src/ee/services/alerts/` |
| `src/services/slack/` (2 files + 1 test) | `src/ee/services/slack/` |
| `src/services/webhook/` (2 files + 1 test) | `src/ee/services/webhook/` |
| `src/services/email/notification-email.service.tsx` | `src/ee/services/email/` |
| `src/services/email/templates/alert-notification-email.tsx` | `src/ee/services/email/templates/` |
| `src/trpc/routers/alerts/` (4 files) | `src/ee/routers/alerts/` |
| `src/trpc/routers/rabbitmq/alerts.ts` | `src/ee/routers/rabbitmq/` |
| `src/trpc/routers/rabbitmq/topology.ts` | `src/ee/routers/rabbitmq/` |
| `src/trpc/routers/workspace/data.ts` | `src/ee/routers/workspace/` |

## Test plan

- [x] `pnpm type-check` — 0 errors
- [x] `pnpm test` — 714/719 pass (4 pre-existing failures unrelated to this change: `Error.isError is not a function` in webhook service tests, Node v20 vs v24 mismatch)
- [ ] Add `PUBLIC_REPO_TOKEN` secret (GitHub PAT with push access to `getqarote/qarote`) to enable the public mirror sync workflow

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **Chores**
  * Added an automated workflow to mirror CE content to a public repository on main.
  * Increased Node memory for staging deployments.
  * Server now composes Enterprise routes when EE is present; CE build no longer exposes EE-only alerts/topology.
  * Added a pluggable alert seeding adaptor so EE can register default alert rules.
  * Added a CE placeholder for workspace data export.

* **Documentation**
  * Added Enterprise Edition license and terms.

### CODE REVIEW

**Comment by briceth** [comment]
## Known follow-up: CE → EE hard dependency

The code review correctly flags that several CE files import from `@/ee/` paths (e.g. `trpc/router.ts`, `email.service.ts`, `trpc/routers/rabbitmq/index.ts`), which means the public CE mirror cannot build independently today.

This is a real architectural gap. The fix requires one of:

- **Plugin/registry pattern** — CE router exposes an extension point; EE registers its routes at bootstrap time
- **Dual router assembly** — `src/trpc/router.ts` (CE-only routes) + `src/ee/trpc/router.ts` (CE + EE merge); server entry point moves to EE
- **Stubs in CE** — CE ships no-op stubs for every EE integration point that the EE layer overrides

This will be addressed in a dedicated follow-up PR. The public mirror is currently scoped to code transparency and is not intended to be independently buildable in this initial split.

**Comment by briceth** [comment]
This branch has been merged into `getqarote/Qarote-EE` (the private EE repo). `getqarote/Qarote` is now a read-only CE mirror — all development happens upstream in the private repo and is synced here automatically. No action needed.
